set_property SRC_FILE_INFO {cfile:C:/2014104101/pwm_test_4/pwm_test_4.srcs/constrs_1/imports/digital_clock_files2/top.xdc rfile:../../../pwm_test_4.srcs/constrs_1/imports/digital_clock_files2/top.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "Y18" [get_ports "resetn"]
set_property src_info {type:XDC file:1 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "M19" [get_ports "clk"]
set_property src_info {type:XDC file:1 line:9 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "P15" [get_ports "pwm_out"]
